### ISSUE TITLE
[🐛 Bug]: Keywords "Double Tap" and "Flick" return WebDriverException: An unknown error occurred

### ISSUE THREAD

**Issue by andrejpu** [Accruent/robotframework-applicationlibrary#14]
### What happened?

Greetings,

During the execution of the tests "Tap Tests" and "Flick Tests" of [WinAppDriver-DesktopTests.robot](https://github.com/Accruent/robotframework-applicationlibrary/blob/master/samples/WinAppDriver-DesktopTests.robot) Robot Framework returns next error:

WebDriverException: Message: An unknown error occurred in the remote end while processing the command.

Error is triggered when using keywords Double Tap And Flick. I'm using WinAppDriver v1.2.1.

Can you please check this? Thanks in advance.

### Relevant log output

```shell
WinAppDriver console:
==========================================
POST /session/F9F8BCC4-5E6B-44C6-B9D8-6E900ED5A2D6/touch/flick HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 83
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.3.0 (selenium/3.141.0 (python windows))

{"xspeed": 100, "yspeed": 100, "sessionId": "F9F8BCC4-5E6B-44C6-B9D8-6E900ED5A2D6"}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
==========================================

Robot Framework console:
Tap Tests                                                             | FAIL |
WebDriverException: Message: An unknown error occurred in the remote end while processing the command.
------------------------------------------------------------------------------
Flick Tests                                                           | FAIL |
WebDriverException: Message: An unknown error occurred in the remote end while processing the command.
```

### Operating System

Windows 10, version 10.0.19043

### RobotFramework-ApplicationLibrary version (tag)

1.0.2

**Comment by Wolfe1** [comment]
@andrejpu Running this locally, I am **not** able to reproduce (using AppLib 1.0.2 and WinAppDriver 1.2.1):

![image](https://user-images.githubusercontent.com/3010366/182861347-9e72a663-ddb9-48af-b536-6fd1a0745947.png)



 Could you try a few things and rerun the tests each time to see if its resolved:

1. Force reinstall ApplicationLibrary: `pip install robotframework-applicationlibrary --force`
2. Repair your installation of WinAppdriver by downloading 1.2.1 and running the installer again with the "repair" option. https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1
3. Uninstall your WinAppDriver installation and install the 1.3 (1.2.99) Release candidate from https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.99

**Comment by andrejpu** [comment]
@Wolfe1 thank you for the quick response.

I try points 2. and 3. due to error coming from the driver's side (not from the library). There was no success, Error is still present.

I moved the tests to another computer with the same version of the library and WinAppDriver: the tests PASSED without any error. It's clear that the first PC has some differences which are currently unknown to me: I checked the updates and both PCs have same updates ...

I'm closing the ticket because the problem is not connected to the applicationlibrary. In case I'll find the problem, I'll report here.

Thanks for support!

**Comment by andrejpu** [comment]
I've found the problem: if I use the "extend" option (2 displays) then the error is reported from WinAppDriver. If I run the tests on a single display (PC screen or Second screen) then the tests PASSED: WinAppDriver does **not** return an error with status 13: _"unknown error","message":"An unknown error occurred in the remote end while processing the command."_

**Comment by Wolfe1** [comment]
@andrejpu Thank you for the update. Yeah this would probably then be an issue for the [WinAppDriver](https://github.com/microsoft/WinAppDriver) repo then. Unfortunately Microsoft has been quite [slow on the updates](https://github.com/microsoft/WinAppDriver/issues/1550) or roadmap....or any communication with the community so I doubt they will fix it in our lifetime.
