### ISSUE TITLE
[🐛 Bug]: [ WARN ] Keyword 'Save Appium Screenshot' could not be run on failure: No application is open

### ISSUE THREAD

**Issue by WilliamMega** [Accruent/robotframework-applicationlibrary#64]
### What happened?

requirements.txt

Appium-Python-Client==1.3.0
decorator==5.1.1
docutils==0.20.1
kitchen==1.2.6
psutil==5.9.4
robotframework==6.0.2
robotframework-appiumlibrary==1.6.4
robotframework-applicationlibrary==1.1.2
selenium==3.141.0
six==1.16.0
urllib3==2.0.2

File: zoombaCalculator.robot

*** Settings ***
Documentation     Zoomba Desktop Library Tests.
Library           ApplicationLibrary.DesktopLibrary
Suite Setup       Driver Setup    C://Program Files//Windows Application Driver//WinAppDriver.exe
Test Setup        Start App Auto System
Test Teardown     Quit Application
Suite Teardown    Driver Teardown
Force Tags        Windows

*** Variables ***
${Remote_Url}           http://127.0.0.1:4723
${AutoSystem}           C://autosystem//main.exe

*** Keywords ***

Start App Auto System
    [Documentation]     Sets up the application for quick launching through 'Launch Application' and starts the AutoSystem
    Open Application    ${Remote_Url}     platformName=Windows    deviceName=Windows   app=${AutoSystem}

*** Test Cases ***
Realizar Login
    Sleep        5s
    Send Keys    ADMIN
    Send Keys    \ue004    p    \ue004
    Send Keys    1
    Send Keys    \ue007    p    \ue007
    Sleep        5s

### Relevant log output

```shell
PS C:\Automacao\Zoomba-FrameWork> robot -d .\report .\calculatorAutomation\zoombaCalculator.robot
==============================================================================
zoombaCalculator :: Zoomba Desktop Library Tests.
==============================================================================
[ WARN ] Keyword 'Save Appium Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Save Appium Screenshot' could not be run on failure: No application is open
Realizar Login                                                        | FAIL |
Setup failed:
ValueError: Timeout value connect was <object object at 0x00000176046D4B80>, but it must be an int, float or None.

Also teardown failed:
No application is open
------------------------------------------------------------------------------
zoombaCalculator :: Zoomba Desktop Library Tests.                     | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\Automacao\Zoomba-FrameWork\report\output.xml
Log:     C:\Automacao\Zoomba-FrameWork\report\log.html
Report:  C:\Automacao\Zoomba-FrameWork\report\report.html
```

### Operating System

Windows 10

### RobotFramework-ApplicationLibrary version (tag)

robotframework-applicationlibrary==1.1.2

**Comment by Wolfe1** [comment]
@WilliamMega The real issue here is "ValueError: Timeout value connect was <object object at 0x00000176046D4B80>, but it must be an int, float or None." which seems to have been caused by a urilib3 issue created in version 2.0.2:

https://github.com/shailshouryya/yt-videos-list/issues/19#issuecomment-1567648359

I am pushing an update now that will require urllib3 1.26.16 which should fix this issue. Please update to latest ApplicationLibrary with **pip install robotframework-applicationlibrary --upgrade** once the new version is released or simply downgrade your own urllib3.
