### ISSUE TITLE
[🚀 Feature]: Changing license to APACHE version 2.0

### ISSUE THREAD

**Issue by JockeJarre** [Accruent/robotframework-applicationlibrary#65]
### Feature and motivation

Would it be possible to change the licence to APACHE version 2.0 as the underlying Appium library?

We would consider to use and help improve what I think is a nice GUI testing library for Robot Framework, but the fact that it uses the GPL prevents us from doing so.

### Usage example

If it would change to APACHE version 2.0, we would continue our investigation.

**Comment by Wolfe1** [comment]
Can't see why not, done.
