### ISSUE TITLE
Effect of WinAppDriver paused Development on ApplicationLibrary

### ISSUE THREAD

**Issue by savitakul** [Accruent/robotframework-applicationlibrary#72]
### Feature and motivation

Hi,
We are checking if RobotFramework-ApplicationLibrary is suitable for out test developement. Our team already have 1000+ tests in Coded UI and looking to shift to robotframework tests. We are considering the applicationLibrary for test shift and new test development but we are bit worried about WinAppDriver paused development.
Can you please provide your view on whether this paused development could cause issue in near future?

### Usage example

Please let us know if there is any update from your side on the same.
Appreciate your help and time!

**Comment by Wolfe1** [comment]
Hey @savitakul,

I would say I feel much the same (you can see a few of my comments throughout https://github.com/microsoft/WinAppDriver/issues/1550#issuecomment-1603993246 as well haha). I do not think this would be a suitable project to move to as we are already seeing issues preventing us to move forward (locked in selenium 3). Microsoft's lack of communication and support here signals to me that if this eventually broke we would not have a fix anytime soon.

**Comment by savitakul** [comment]
Hi @Wolfe1,

Greatly Appreciate your view, We were looking forward for the library implementation in our environment. But i think it will be best to wait little more and find out what Microsoft planned!

Thanks for your valuable time :)

**Comment by daluu** [comment]
On this note, perhaps it would be useful for someone to fork and port this RF library to be internally swappable to use a different underlying tool. If you look at the WinAppDriver issue discussion @Wolfe1 referred to, I believe there were references to alternative tools, some designed similar to WinAppDriver for interfacing, so those are good candidates to swap WinAppDriver with. My two cents. As a way to make this RF library useful while the underlying tool is having issues.

**Comment by viiker** [comment]
Hi @daluu ,
Do you know of any current tools that can replace WinAppDriver? Thanks.

**Comment by daluu** [comment]
@viiker I don't currently work with GUI automation tools to know which ones work best as a replacement for WinAppDriver, but I did curate a list of bookmarks myself of other candidates, that I did over time. Here's a list below that I pulled off my GH bookmarks. I would try starting off with the other projects that have "WinAppDriver" in the name.

Now these might not be direct replacements in that they may or may not be WebDriver protocol (or Appium/Selenium) and Selenium Grid compatible. If they are not, someone will have to wrap them in a wrapper interface to expose the WebDriver JSONWireProtocol for those tools. I think the ones with "driver" in the tool name should be more likely compatible.

https://github.com/jalian-systems/javadriver-examples
https://github.com/Danp2/au3WebDriver
https://github.com/rainmanwy/robotframework-SikuliLibrary
https://github.com/jaredfin/SikuliXRobotLibrary
https://github.com/FlaUI/FlaUI/issues/50 or https://github.com/FlaUI/FlaUI/issues/227
https://github.com/MicrosoftDocs/winui-api
https://github.com/licanhua/YWinAppDriver
https://nutjs.dev/
https://github.com/2gis/Winium.Desktop
https://github.com/cuketest/leanrunner
https://github.com/lanit-exp/FlaNium.Desktop.Driver
https://github.com/stoneman/appium-windows-driver
https://github.com/kfrajtak/WinAppDriver
https://github.com/arkottke/winguiauto

https://github.com/yinkaisheng/Python-UIAutomation-for-Windows
https://github.com/claudiobizzotto/pyautogui-with-selenium
https://github.com/octalmage/robotjs
https://github.com/imsardine/pyuia
https://github.com/imsardine/winappdriver

https://github.com/RaiMan/SikuliX1/issues/477

https://github.com/GDATASoftwareAG/robotframework-flaui
https://github.com/MicroFocus/SilkAppDriver
https://github.com/jatalahd/WhiteRobotLibrary
