### ISSUE TITLE
[🚀 Feature]: Upgrade Selenium dependency

### ISSUE THREAD

**Issue by jonathan-fortin** [Accruent/robotframework-applicationlibrary#75]
### Feature and motivation

Hi,

Is it possible to upgrade the Selenium dependency to 4.x or the latest version 4.10.0?

You are using version 3.141.0 released in 2018, and we are using other libraries that require a newer version.

I await your response.

Regards

### Usage example

N/A

**Comment by Wolfe1** [comment]
Unfortunately we can not upgrade to selenium 4 due to a still exiting constraint on the WinAppDriver side.

We originally split this project off of robotframework-zoomba for this exact reason.

See https://github.com/Accruent/robotframework-zoomba/releases/tag/3.0.0 for more information.
