### ISSUE TITLE
[🚀 Feature]: Dependent selenium version is too low

### ISSUE THREAD

**Issue by viiker** [Accruent/robotframework-applicationlibrary#80]
### Feature and motivation

The requirements.txt indicates:
robotframework>=5.0
selenium==3.141.0
robotframework-appiumlibrary==1.6.4
psutil>=5.6.0
Appium-Python-Client==1.3.0
urllib3<=1.26.16

The dependent selenium version is 3.141.0. 
Can this version restriction be loosened?

### Usage example

Can it be changed to:
selenium>=3.141.0

**Comment by Wolfe1** [comment]
No, it will not function with selenium 4 and above.

https://github.com/Accruent/robotframework-applicationlibrary/issues/75
